# Translates site/en.source.html into site/da.source.html (the Danish front page).
# Every pair must match exactly; the script lists the ones that no longer do.
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
en = open('en.source.html').read()


T = [
 ('<a class="t-toggle lang-toggle" role="switch" aria-checked="true" data-on="true" href="./" hreflang="da" aria-label="Language: English. Switch to Danish"><span class="t-toggle-thumb" aria-hidden="true"></span><span class="lt" lang="da">DK</span><span class="lt" lang="en">EN</span></a>', '<a class="t-toggle lang-toggle" role="switch" aria-checked="false" data-on="false" href="en.html" hreflang="en" aria-label="Sprog: dansk. Skift til engelsk"><span class="t-toggle-thumb" aria-hidden="true"></span><span class="lt" lang="da">DK</span><span class="lt" lang="en">EN</span></a>'),
 ('aria-label="Claude on iPhone answering from sundhed.dk when the last tetanus vaccination was"', 'aria-label="Claude på iPhone svarer ud fra sundhed.dk, hvornår den seneste stivkrampevaccination var"'),
 ('aria-label="SundhedMCP home"', 'aria-label="SundhedMCP forside"'),
 ('<nav aria-label="Sections">', '<nav aria-label="Afsnit">'),
 ('<a href="#how">How it works</a>', '<a href="#how">Sådan virker det</a>'),
 ('<a href="#reads">What it reads</a>', '<a href="#reads">Hvad den læser</a>'),
 ('<a href="#privacy">Privacy</a>', '<a href="#privacy">Privatliv</a>'),
 ('<a href="#faq">Questions</a>', '<a href="#faq">Spørgsmål</a>'),
 ('<a class="cta" href="#run">Get started</a>', '<a class="cta" href="#run">Kom i gang</a>'),
 ('Your health record.<br>Now in your AI.', 'Din sundhedsjournal.<br>Nu i din AI.'),
 ('Ask Claude about your medicine, prescriptions, test results and vaccinations from sundhed.dk. You log in with MitID. Your data stays on your own machine or server.',
  'Spørg Claude om din medicin, dine recepter, prøvesvar og vaccinationer fra sundhed.dk. Du logger på med MitID. Dine data bliver på din egen computer eller server.'),
 ('<a class="btn primary" href="#run">Get started</a>', '<a class="btn primary" href="#run">Kom i gang</a>'),
 ('See how it works<span', 'Se hvordan det virker<span'),
 ('Free and open source · In development · Not affiliated with sundhed.dk', 'Gratis og open source · Under udvikling · Ikke tilknyttet sundhed.dk'),
 ('aria-label="Example: Claude answering from SundhedMCP"', 'aria-label="Eksempel: Claude svarer fra SundhedMCP"'),
 ('Which of my prescriptions run out soon?', 'Hvilke af mine recepter udløber snart?'),
 ('Reading your prescriptions on sundhed.dk…', 'Læser dine recepter på sundhed.dk…'),
 ('data-text="get_prescriptions · 4 open prescriptions"><code>get_prescriptions</code> · 4 open prescriptions',
  'data-text="get_prescriptions · 4 åbne recepter"><code>get_prescriptions</code> · 4 åbne recepter'),
 ('Two need attention. <b>Metformin</b> has one dispensing left, and <b>Ventoline</b> expires on <b>14 Oct</b>. Ask your GP to renew both.',
  'To kræver opmærksomhed. <b>Metformin</b> har én udlevering tilbage, og <b>Ventoline</b> udløber <b>14. okt.</b> Bed din læge om at forny begge.'),
 ('<span>Medicine</span><span>Dispensings left</span><span class="date">Valid until</span>', '<span>Medicin</span><span>Udleveringer tilbage</span><span class="date">Gyldig til</span>'),
 ('500 mg · 1 tablet twice daily', '500 mg · 1 tablet 2 gange dagligt'),
 ('1 of 4</div><div class="date">02.03.2027', '1 af 4</div><div class="date">02.03.2027'),
 ('0.2 mg/dose · as needed', '0,2 mg/dosis · efter behov'),
 ('1 of 2</div>', '1 af 2</div>'),
 ('20 mg · 1 tablet in the evening</small>', '20 mg · 1 tablet om aftenen</small>'),
 ('3 of 4</div>', '3 af 4</div>'),
 ('<p class="eyebrow">How it works</p>', '<p class="eyebrow">Sådan virker det</p>'),
 ('<h2>How SundhedMCP works</h2>', '<h2>Sådan virker SundhedMCP</h2>'),
 ('sundhed.dk has no API for citizens. So SundhedMCP does what your browser does: you log in with MitID, and it reads the same pages you see on Min Side.',
  'sundhed.dk har ingen API for borgere. Så SundhedMCP gør det samme som din browser: du logger på med MitID, og den læser de samme sider, som du ser på Min Side.'),
 ('<h3>Add it to your AI</h3><p>One command in Claude Code, or a custom connector in claude.ai when you host it on Railway. Works with any MCP client.</p>',
  '<h3>Tilføj den til din AI</h3><p>Én kommando i Claude Code, eller en custom connector i claude.ai, når du kører den på Railway. Virker med alle MCP-klienter.</p>'),
 ('alt="The MitID login on NemLog-in: Log on at Sundhed.dk, with a user ID field and a Continue button"',
  'alt="MitID-login på NemLog-in: Log på hos Sundhed.dk, med felt til bruger-ID og en Fortsæt-knap"'),
 ('<h3>Log in with MitID</h3><p>The real MitID login opens, ready for your user ID. Type it, then approve in your MitID app like any other login. Hosted, do this on a computer: MitID may ask for a QR code, scanned with the app on your phone.</p>',
  '<h3>Log på med MitID</h3><p>Det rigtige MitID-login åbner, klar til dit bruger-ID. Skriv det, og godkend i MitID-appen som ved ethvert andet login. Er den hostet, så gør det på en computer: MitID kan bede om en QR-kode, som du scanner med appen på din telefon.</p>'),
 ('alt="Claude on iPhone answering in Danish when the last tetanus vaccination was, from sundhed.dk"',
  'alt="Claude på iPhone svarer på dansk, hvornår den seneste stivkrampevaccination var, ud fra sundhed.dk"'),
 ('<h3>Ask anything</h3><p>Your AI picks the right tool and answers from your own record, in plain words and in your language.</p>',
  '<h3>Spørg om alt</h3><p>Din AI vælger det rigtige værktøj og svarer ud fra din egen journal, i et klart sprog og på dansk.</p>'),
 ('<a class="btn line" href="https://github.com/manas-katyal/sundhedmcp">View on GitHub</a>', '<a class="btn line" href="https://github.com/manas-katyal/sundhedmcp">Se koden på GitHub</a>'),
 ('<p class="eyebrow">What it reads</p>', '<p class="eyebrow">Hvad den læser</p>'),
 ('<h2>Everything on Min Side. Nothing more.</h2>', '<h2>Alt på Min Side. Intet mere.</h2>'),
 ('<p>Five parts of your health record, each a read-only tool.</p>', '<p>Fem dele af din sundhedsjournal, hver som et værktøj, der kun kan læse.</p>'),
 ('<h3>Your medicine card.</h3>', '<h3>Dit medicinkort.</h3>'),
 ('<p>Every medicine you take, with strength, dosage, reason, ATC code and who prescribed it.</p>', '<p>Al den medicin, du tager, med styrke, dosering, årsag, ATC-kode og hvem der har ordineret den.</p>'),
 ('aria-label="Example medicine card"', 'aria-label="Eksempel på medicinkort"'),
 ('<span>1 tablet twice daily</span>', '<span>1 tablet 2 gange dagligt</span>'),
 ('<span>1 tablet in the evening</span>', '<span>1 tablet om aftenen</span>'),
 ('Ventoline Diskus 0.2 mg/dose<span>1–2 puffs as needed</span>', 'Ventoline Diskus 0,2 mg/dosis<span>1–2 pust efter behov</span>'),
 ('<span>1 tablet daily, May–Aug</span>', '<span>1 tablet dagligt, maj–aug.</span>'),
 ('<h3>Prescriptions.</h3>', '<h3>Recepter.</h3>'),
 ('<p>Dispensings left, expiry dates and pharmacy.</p>', '<p>Udleveringer tilbage, udløbsdatoer og apotek.</p>'),
 ('<small>of 4 left</small>', '<small>af 4 tilbage</small>'),
 ('<h3>Vaccinations.</h3>', '<h3>Vaccinationer.</h3>'),
 ('<p>What each one covers, and for how long.</p>', '<p>Hvad hver enkelt dækker, og hvor længe.</p>'),
 ('<small>next tetanus</small>', '<small>næste stivkrampe</small>'),
 ('<h3>Referrals.</h3>', '<h3>Henvisninger.</h3>'),
 ('<p>Active and earlier referrals to specialists and hospitals.</p>', '<p>Aktive og tidligere henvisninger til speciallæger og sygehuse.</p>'),
 ('<h3>Test results.</h3>', '<h3>Prøvesvar.</h3>'),
 ('<p>Blood tests and lab results from the regions, for any date range. Ask how a value has changed over the years.</p>',
  '<p>Blodprøver og laboratoriesvar fra regionerne, for enhver periode. Spørg, hvordan en værdi har udviklet sig over årene.</p>'),
 ('Example data. Your own record is only ever shown to you and your AI.', 'Eksempeldata. Din egen journal vises kun for dig og din AI.'),
 ('<p class="eyebrow">Privacy</p>', '<p class="eyebrow">Privatliv</p>'),
 ('<h2>Private by design.</h2>', '<h2>Privat fra starten.</h2>'),
 ('<p>Your health record is yours. SundhedMCP is built so it stays that way.</p>', '<p>Din sundhedsjournal er din. SundhedMCP er bygget, så det forbliver sådan.</p>'),
 ('<h3>You approve every login.</h3><p>You log in on the real MitID page and approve in your own MitID app. There is no password to hand over, and nothing happens until you approve.</p>',
  '<h3>Du godkender hvert login.</h3><p>Du logger på den rigtige MitID-side og godkender i din egen MitID-app. Der er ingen adgangskode at give fra dig, og intet sker, før du godkender.</p>'),
 ('<h3>Only on your own server.</h3><p>Run locally, everything lives in memory and is gone when you stop SundhedMCP. Hosted, your server keeps one copy of your record on its own volume, fetched after each login, so you can ask from your phone. No telemetry.</p>',
  '<h3>Kun på din egen server.</h3><p>Kører du lokalt, ligger alt i hukommelsen og forsvinder, når du stopper SundhedMCP. Hostet gemmer din server én kopi af din journal på sit eget volume, hentet efter hvert login, så du kan spørge fra telefonen. Ingen telemetri.</p>'),
 ('<h3>Read-only.</h3><p>It can read your record. It cannot renew a prescription, change your medicine card or send a message.</p>',
  '<h3>Kun læseadgang.</h3><p>Den kan læse din journal. Den kan ikke forny en recept, ændre dit medicinkort eller sende en besked.</p>'),
 ('<h3>CPR stays out.</h3><p>Your CPR number is masked in every answer before your AI sees it.</p>',
  '<h3>CPR holdes ude.</h3><p>Dit CPR-nummer er skjult i hvert svar, før din AI ser det.</p>'),
 ('<h3>Runs where you choose.</h3><p>On your own computer, or on a server you control. There is no SundhedMCP company in between.</p>',
  '<h3>Kører, hvor du vælger.</h3><p>På din egen computer eller på en server, du selv styrer. Der er intet SundhedMCP-firma imellem.</p>'),
 ('<p>MIT licensed and small enough to read in an afternoon. <a href="https://github.com/manas-katyal/sundhedmcp">Check it yourself</a>.</p>',
  '<p>MIT-licens og lille nok til at læse på en eftermiddag. <a href="https://github.com/manas-katyal/sundhedmcp">Tjek det selv</a>.</p>'),
 ('<p class="eyebrow">Get started</p>', '<p class="eyebrow">Kom i gang</p>'),
 ('<h2>Two ways to run it.</h2>', '<h2>To måder at køre den på.</h2>'),
 ('<p>Both read the same record with the same tools. Pick where the browser that holds your login should live.</p>',
  '<p>Begge læser den samme journal med de samme værktøjer. Vælg, hvor browseren med dit login skal køre.</p>'),
 ('aria-label="Where to run SundhedMCP"', 'aria-label="Hvor SundhedMCP skal køre"'),
 ('aria-selected="true">On your computer</button>', 'aria-selected="true">På din computer</button>'),
 ('aria-selected="false">On a server</button>', 'aria-selected="false">På en server</button>'),
 ('<p class="da">On your computer</p>', '<p class="da">På din computer</p>'),
 ('<h3>Local.</h3>', '<h3>Lokalt.</h3>'),
 ('<p>For Claude Code, Claude Desktop and Cursor. A browser window opens for MitID and minimizes itself.</p>',
  '<p>Til Claude Code, Claude Desktop og Cursor. Et browservindue åbner til MitID og minimerer sig selv bagefter.</p>'),
 ('<li>Your data never leaves your machine, except to your AI</li><li>Needs Node 24 and Chrome or Edge</li>',
  '<li>Dine data forlader aldrig din computer, undtagen til din AI</li><li>Kræver Node 24 og Chrome eller Edge</li>'),
 ('aria-label="Copy command"', 'aria-label="Kopiér kommando"'),
 ('aria-label="Copy commands"', 'aria-label="Kopiér kommandoer"'),
 ('<span class="t-text-swap">Copy</span>', '<span class="t-text-swap">Kopiér</span>'),
 ('<p class="da">On your own server</p>', '<p class="da">På din egen server</p>'),
 ('<h3>Hosted.</h3>', '<h3>Hostet.</h3>'),
 ('<p>For claude.ai and your phone. Deploy to Railway in a few minutes. You log in with MitID on a password-protected page on your own server.</p>',
  '<p>Til claude.ai og din telefon. Læg den på Railway på få minutter. Du logger på med MitID på en adgangskodebeskyttet side på din egen server.</p>'),
 ('<b>Deploy to Railway.</b> With the <a href="https://docs.railway.com/guides/cli">Railway CLI</a>, from a copy of the code:',
  '<b>Læg den på Railway.</b> Med <a href="https://docs.railway.com/guides/cli">Railway CLI</a>, fra en kopi af koden:'),
 ('<b>Add it to claude.ai.</b> Settings → Connectors → Add custom connector, with your Railway address plus <code>/mcp</code>. Sign in with the password.',
  '<b>Tilføj den i claude.ai.</b> Settings → Connectors → Add custom connector, med din Railway-adresse plus <code>/mcp</code>. Log ind med adgangskoden.'),
 ('<b>Log in with MitID.</b> Ask Claude anything about your health. It sends you a link to your server: open it on a computer, not your phone, and scan the QR code with the MitID app on your phone.',
  '<b>Log på med MitID.</b> Spørg Claude om noget om dit helbred. Du får et link til din server: åbn det på en computer, ikke din telefon, og scan QR-koden med MitID-appen på din telefon.'),
 ("Any Docker host works too: the image needs <code>ADMIN_PASSWORD</code> and a volume at <code>/data</code>. Your data passes through your server's memory and is never stored.",
  'Alle Docker-hosts virker også: imaget skal have <code>ADMIN_PASSWORD</code> og et volume på <code>/data</code>. Dine data passerer gennem serverens hukommelse og gemmes aldrig.'),
 ('In development: the npm package is not published yet, so run it locally <a href="https://github.com/manas-katyal/sundhedmcp">from source</a>. Railway builds from source already.',
  'Under udvikling: npm-pakken er ikke udgivet endnu, så kør den lokalt <a href="https://github.com/manas-katyal/sundhedmcp">fra kildekoden</a>. Railway bygger allerede fra kildekoden.'),
 ('<p>For claude.ai and your phone. Your own server on Railway, set up with one click. You log in with MitID on a password-protected page on it.</p>', '<p>Til claude.ai og din telefon. Din egen server på Railway, sat op med ét klik. Du logger på med MitID på en adgangskodebeskyttet side på den.</p>'),
 ('<b>Deploy on Railway.</b> One click creates your own server with the right volume and address. It takes a few minutes.', '<b>Læg den på Railway.</b> Ét klik opretter din egen server med det rigtige volume og en adresse. Det tager et par minutter.'),
 ('sundhedmcp">Deploy on Railway</a>', 'sundhedmcp">Deploy på Railway</a>'),
 ("<b>Choose a password.</b> Open your server's address from Railway. The first page asks you to choose the password that protects it.", '<b>Vælg en adgangskode.</b> Åbn din servers adresse fra Railway. Den første side beder dig vælge den adgangskode, der beskytter den.'),
 ("Any Docker host works too: run <code>ghcr.io/manas-katyal/sundhedmcp</code> with a volume at <code>/data</code>. After each login your server keeps a copy of your record on that volume, and nobody else gets it.", 'Alle Docker-hosts virker også: kør <code>ghcr.io/manas-katyal/sundhedmcp</code> med et volume på <code>/data</code>. Efter hvert login gemmer din server en kopi af din journal på det volume, og ingen andre får den.'),
 ('In development: the npm package is not published yet, so run it locally <a href="https://github.com/manas-katyal/sundhedmcp">from source</a>.', 'Under udvikling: npm-pakken er ikke udgivet endnu, så kør den lokalt <a href="https://github.com/manas-katyal/sundhedmcp">fra kildekoden</a>.'),
 ('<h2>Questions.</h2>', '<h2>Spørgsmål.</h2>'),
 ('Is this made by sundhed.dk?<span', 'Er det lavet af sundhed.dk?<span'),
 ('No. SundhedMCP is an independent open-source project, not affiliated with sundhed.dk, Sundhedsdatastyrelsen or MitID.',
  'Nej. SundhedMCP er et uafhængigt open source-projekt, som ikke er tilknyttet sundhed.dk, Sundhedsdatastyrelsen eller MitID.'),
 ('Why do I have to log in again?<span', 'Hvorfor skal jeg logge på igen?<span'),
 ('sundhed.dk ends sessions after a while, and SundhedMCP does not keep your login. When a tool says the session has ended, say "connect sundhed.dk" and approve in MitID again.',
  'sundhed.dk afslutter sessioner efter et stykke tid, og SundhedMCP gemmer ikke dit login. Når et værktøj siger, at sessionen er slut, så bed om at forbinde til sundhed.dk og godkend i MitID igen.'),
 ('Can I run it for my family or patients?<span', 'Kan jeg køre den for min familie eller mine patienter?<span'),
 ("No. It is for one person reading their own record. A service holding other people's health data needs approvals and agreements it does not have.",
  'Nej. Den er til én person, der læser sin egen journal. En tjeneste med andres helbredsdata kræver godkendelser og aftaler, som den ikke har.'),
 ('Is my data sent anywhere?<span', 'Bliver mine data sendt nogen steder hen?<span'),
 ("Only to the AI you ask. Locally, it goes from sundhed.dk to your computer to your AI. Hosted, it passes through your own server's memory on the way.",
  'Kun til den AI, du spørger. Lokalt går de fra sundhed.dk til din computer og videre til din AI. Hostet passerer de gennem din egen servers hukommelse på vejen.'),
 ('Is this medical advice?<span', 'Er det lægelig rådgivning?<span'),
 ('No. Your AI can read and summarise your record, but it is not your doctor. Talk to your GP or pharmacist before changing how you take any medicine.',
  'Nej. Din AI kan læse og opsummere din journal, men den er ikke din læge. Tal med din egen læge eller dit apotek, før du ændrer, hvordan du tager din medicin.'),
 ('Why do I log in on a computer?<span', 'Hvorfor logger jeg på fra en computer?<span'),
 ('Hosted, MitID does not recognise the server\'s browser and asks for a QR code instead of your user ID. That code must be scanned with the MitID app on your phone, so open the login link on a computer and keep your phone free to scan it.',
  'Er den hostet, genkender MitID ikke serverens browser og beder om en QR-kode i stedet for dit bruger-ID. Koden skal scannes med MitID-appen på din telefon, så åbn login-linket på en computer og hold telefonen fri til at scanne den.'),
 ('<h2>Ask your health record anything.</h2>', '<h2>Spørg din sundhedsjournal om alt.</h2>'),
 ('View on GitHub<span', 'Se koden på GitHub<span'),
 ('SundhedMCP reads your own record on sundhed.dk after you log in with MitID. It is not affiliated with sundhed.dk, Sundhedsdatastyrelsen or MitID, and it is not medical advice. Examples on this page use made-up data.',
  'SundhedMCP læser din egen journal på sundhed.dk, efter du har logget på med MitID. Den er ikke tilknyttet sundhed.dk, Sundhedsdatastyrelsen eller MitID, og den er ikke lægelig rådgivning. Eksemplerne på siden bruger opdigtede data.'),
 ('<span>MIT licensed · sundhedmcp.dk</span>', '<span>MIT-licens · sundhedmcp.dk</span>'),
 ('<span>Made by <a href="https://github.com/manas-katyal">manas-katyal</a>', '<span>Lavet af <a href="https://github.com/manas-katyal">manas-katyal</a>'),
 ('swapText(label, "Selected")', 'swapText(label, "Markeret")'),
 ('swapText(label, "Copied")', 'swapText(label, "Kopieret")'),
 ('swapText(label, "Copy")', 'swapText(label, "Kopiér")'),
]
da = open('en.source.html').read()
missing = []
for a, b in T:
    if a not in da:
        missing.append(a[:70])
        continue
    da = da.replace(a, b)
print("missing:", missing)
open('da.source.html', 'w').write(da)
