# Translates site/en.source.html into site/da.source.html (the Danish front page).
# Every pair must match exactly; the script lists the ones that no longer do.
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
en = open('en.source.html').read()


T = [
 ('<a class="t-toggle lang-toggle" role="switch" aria-checked="true" data-on="true" href="./" hreflang="da" aria-label="Language: English. Switch to Danish"><span class="t-toggle-thumb" aria-hidden="true"></span><span class="lt" lang="da">DK</span><span class="lt" lang="en">EN</span></a>', '<a class="t-toggle lang-toggle" role="switch" aria-checked="false" data-on="false" href="en.html" hreflang="en" aria-label="Sprog: dansk. Skift til engelsk"><span class="t-toggle-thumb" aria-hidden="true"></span><span class="lt" lang="da">DK</span><span class="lt" lang="en">EN</span></a>'),
 ('aria-label="Claude on iPhone answering from sundhed.dk when the last tetanus vaccination was"', 'aria-label="Claude på iPhone svarer ud fra sundhed.dk, hvornår den seneste stivkrampevaccination var"'),
 ('aria-label="SundhedMCP home"', 'aria-label="SundhedMCP forside"'),
 ('<nav aria-label="Sections">', '<nav aria-label="Afsnit">'),
 ('<a href="#how">How it works</a>', '<a href="#how">Sådan virker det</a>'),
 ('<a href="#reads">What it reads</a>', '<a href="#reads">Hvad den læser</a>'),
 ('<a href="#privacy">Privacy</a>', '<a href="#privacy">Privatliv</a>'),
 ('<a href="#faq">Questions</a>', '<a href="#faq">Spørgsmål</a>'),
 ('<a class="cta" href="#run">Get started</a>', '<a class="cta" href="#run">Kom i gang</a>'),
 ('Your health record.<br>Now in your AI.', 'Din sundhedsjournal.<br>Nu i din AI.'),
 ('<a class="btn primary" href="#run">Get started</a>', '<a class="btn primary" href="#run">Kom i gang</a>'),
 ('See how it works<span', 'Se hvordan det virker<span'),
 ('Free and open source · In development · Not affiliated with sundhed.dk', 'Gratis og open source · Under udvikling · Ikke tilknyttet sundhed.dk'),
 ('<p class="eyebrow">How it works</p>', '<p class="eyebrow">Sådan virker det</p>'),
 ('<h2>How SundhedMCP works</h2>', '<h2>Sådan virker SundhedMCP</h2>'),
 ('sundhed.dk has no API for citizens. So SundhedMCP does what your browser does: you log in with MitID, and it reads the same pages you see on Min Side.',
  'sundhed.dk har ingen API for borgere. Så SundhedMCP gør det samme som din browser: du logger på med MitID, og den læser de samme sider, som du ser på Min Side.'),
 ('alt="The MitID login on NemLog-in: Log on at Sundhed.dk, with a user ID field and a Continue button"',
  'alt="MitID-login på NemLog-in: Log på hos Sundhed.dk, med felt til bruger-ID og en Fortsæt-knap"'),
 ('alt="Claude on iPhone answering in Danish when the last tetanus vaccination was, from sundhed.dk"',
  'alt="Claude på iPhone svarer på dansk, hvornår den seneste stivkrampevaccination var, ud fra sundhed.dk"'),
 ('<h3>Ask anything</h3><p>Your AI picks the right tool and answers from your own record, in plain words and in your language.</p>',
  '<h3>Spørg om alt</h3><p>Din AI vælger det rigtige værktøj og svarer ud fra din egen journal, i et klart sprog og på dansk.</p>'),
 ('<a class="btn line" href="https://github.com/manas-katyal/sundhedmcp">View on GitHub</a>', '<a class="btn line" href="https://github.com/manas-katyal/sundhedmcp">Se koden på GitHub</a>'),
 ('<p class="eyebrow">What it reads</p>', '<p class="eyebrow">Hvad den læser</p>'),
 ('<h2>Everything on Min Side. Nothing more.</h2>', '<h2>Alt på Min Side. Intet mere.</h2>'),
 ('<p>Five parts of your health record, each a read-only tool.</p>', '<p>Fem dele af din sundhedsjournal, hver som et værktøj, der kun kan læse.</p>'),
 ('<h3>Your medicine card.</h3>', '<h3>Dit medicinkort.</h3>'),
 ('<p>Every medicine you take, with strength, dosage, reason, ATC code and who prescribed it.</p>', '<p>Al den medicin, du tager, med styrke, dosering, årsag, ATC-kode og hvem der har ordineret den.</p>'),
 ('aria-label="Example medicine card"', 'aria-label="Eksempel på medicinkort"'),
 ('<span>1 tablet twice daily</span>', '<span>1 tablet 2 gange dagligt</span>'),
 ('<span>1 tablet in the evening</span>', '<span>1 tablet om aftenen</span>'),
 ('Ventoline Diskus 0.2 mg/dose<span>1–2 puffs as needed</span>', 'Ventoline Diskus 0,2 mg/dosis<span>1–2 pust efter behov</span>'),
 ('<span>1 tablet daily, May–Aug</span>', '<span>1 tablet dagligt, maj–aug.</span>'),
 ('<h3>Prescriptions.</h3>', '<h3>Recepter.</h3>'),
 ('<p>Dispensings left, expiry dates and pharmacy.</p>', '<p>Udleveringer tilbage, udløbsdatoer og apotek.</p>'),
 ('<small>of 4 left</small>', '<small>af 4 tilbage</small>'),
 ('<h3>Vaccinations.</h3>', '<h3>Vaccinationer.</h3>'),
 ('<p>What each one covers, and for how long.</p>', '<p>Hvad hver enkelt dækker, og hvor længe.</p>'),
 ('<small>next tetanus</small>', '<small>næste stivkrampe</small>'),
 ('<h3>Referrals.</h3>', '<h3>Henvisninger.</h3>'),
 ('<p>Active and earlier referrals to specialists and hospitals.</p>', '<p>Aktive og tidligere henvisninger til speciallæger og sygehuse.</p>'),
 ('<h3>Test results.</h3>', '<h3>Prøvesvar.</h3>'),
 ('<p>Blood tests and lab results from the regions, for any date range. Ask how a value has changed over the years.</p>',
  '<p>Blodprøver og laboratoriesvar fra regionerne, for enhver periode. Spørg, hvordan en værdi har udviklet sig over årene.</p>'),
 ('Example data. Your own record is only ever shown to you and your AI.', 'Eksempeldata. Din egen journal vises kun for dig og din AI.'),
 ('<p class="eyebrow">Privacy</p>', '<p class="eyebrow">Privatliv</p>'),
 ('<h2>Private by design.</h2>', '<h2>Privat fra starten.</h2>'),
 ('<p>Your health record is yours. SundhedMCP is built so it stays that way.</p>', '<p>Din sundhedsjournal er din. SundhedMCP er bygget, så det forbliver sådan.</p>'),
 ('<h3>You approve every login.</h3><p>You log in on the real MitID page and approve in your own MitID app. There is no password to hand over, and nothing happens until you approve.</p>',
  '<h3>Du godkender hvert login.</h3><p>Du logger på den rigtige MitID-side og godkender i din egen MitID-app. Der er ingen adgangskode at give fra dig, og intet sker, før du godkender.</p>'),
 ('<h3>Read-only.</h3><p>It can read your record. It cannot renew a prescription, change your medicine card or send a message.</p>',
  '<h3>Kun læseadgang.</h3><p>Den kan læse din journal. Den kan ikke forny en recept, ændre dit medicinkort eller sende en besked.</p>'),
 ('<h3>CPR stays out.</h3><p>Your CPR number is masked in every answer before your AI sees it.</p>',
  '<h3>CPR holdes ude.</h3><p>Dit CPR-nummer er skjult i hvert svar, før din AI ser det.</p>'),
 ('<p>MIT licensed and small enough to read in an afternoon. <a href="https://github.com/manas-katyal/sundhedmcp">Check it yourself</a>.</p>',
  '<p>MIT-licens og lille nok til at læse på en eftermiddag. <a href="https://github.com/manas-katyal/sundhedmcp">Tjek det selv</a>.</p>'),
 ('<p class="eyebrow">Get started</p>', '<p class="eyebrow">Kom i gang</p>'),
 ('<p class="da">On your computer</p>', '<p class="da">På din computer</p>'),
 ('<h3>Local.</h3>', '<h3>Lokalt.</h3>'),
 ('<p>For Claude Code, Claude Desktop and Cursor. A browser window opens for MitID and minimizes itself.</p>',
  '<p>Til Claude Code, Claude Desktop og Cursor. Et browservindue åbner til MitID og minimerer sig selv bagefter.</p>'),
 ('aria-label="Copy command"', 'aria-label="Kopiér kommando"'),
 ('<span class="t-text-swap">Copy</span>', '<span class="t-text-swap">Kopiér</span>'),
 ('<h2>Questions.</h2>', '<h2>Spørgsmål.</h2>'),
 ('Is this made by sundhed.dk?<span', 'Er det lavet af sundhed.dk?<span'),
 ('No. SundhedMCP is an independent open-source project, not affiliated with sundhed.dk, Sundhedsdatastyrelsen or MitID.',
  'Nej. SundhedMCP er et uafhængigt open source-projekt, som ikke er tilknyttet sundhed.dk, Sundhedsdatastyrelsen eller MitID.'),
 ('Why do I have to log in again?<span', 'Hvorfor skal jeg logge på igen?<span'),
 ('sundhed.dk ends sessions after a while, and SundhedMCP does not keep your login. When a tool says the session has ended, say "connect sundhed.dk" and approve in MitID again.',
  'sundhed.dk afslutter sessioner efter et stykke tid, og SundhedMCP gemmer ikke dit login. Når et værktøj siger, at sessionen er slut, så bed om at forbinde til sundhed.dk og godkend i MitID igen.'),
 ('Can I run it for my family or patients?<span', 'Kan jeg køre den for min familie eller mine patienter?<span'),
 ("No. It is for one person reading their own record. A service holding other people's health data needs approvals and agreements it does not have.",
  'Nej. Den er til én person, der læser sin egen journal. En tjeneste med andres helbredsdata kræver godkendelser og aftaler, som den ikke har.'),
 ('Is my data sent anywhere?<span', 'Bliver mine data sendt nogen steder hen?<span'),
 ('Is this medical advice?<span', 'Er det lægelig rådgivning?<span'),
 ('<h2>Ask your health record anything.</h2>', '<h2>Spørg din sundhedsjournal om alt.</h2>'),
 ('View on GitHub<span', 'Se koden på GitHub<span'),
 ('SundhedMCP reads your own record on sundhed.dk after you log in with MitID. It is not affiliated with sundhed.dk, Sundhedsdatastyrelsen or MitID, and it is not medical advice. Examples on this page use made-up data.',
  'SundhedMCP læser din egen journal på sundhed.dk, efter du har logget på med MitID. Den er ikke tilknyttet sundhed.dk, Sundhedsdatastyrelsen eller MitID, og den er ikke lægelig rådgivning. Eksemplerne på siden bruger opdigtede data.'),
 ('<span>MIT licensed · sundhedmcp.dk</span>', '<span>MIT-licens · sundhedmcp.dk</span>'),
 ('<span>Made by <a href="https://github.com/manas-katyal">manas-katyal</a>', '<span>Lavet af <a href="https://github.com/manas-katyal">manas-katyal</a>'),
 ('swapText(label, "Selected")', 'swapText(label, "Markeret")'),
 ('swapText(label, "Copied")', 'swapText(label, "Kopieret")'),
 ('swapText(label, "Copy")', 'swapText(label, "Kopiér")'),
 ('Ask Claude about your medicine, prescriptions, test results and vaccinations from sundhed.dk. You log in with MitID. It runs on your own computer, and what your AI reads goes to your AI provider.',
  'Spørg Claude om din medicin, dine recepter, prøvesvar og vaccinationer fra sundhed.dk. Du logger på med MitID. Den kører på din egen computer, og det, din AI læser, sendes til din AI-udbyder.'),
 ('<h3>Add it to your AI</h3><p>One command in Claude Code or Claude Desktop, on your own computer. Works with any local MCP client.</p>',
  '<h3>Tilføj den til din AI</h3><p>Én kommando i Claude Code eller Claude Desktop, på din egen computer. Virker med alle lokale MCP-klienter.</p>'),
 ('<h3>Log in with MitID</h3><p>The real MitID login opens in a window on your computer, ready for your user ID. Type it, then approve in your MitID app like any other login.</p>',
  '<h3>Log på med MitID</h3><p>Det rigtige MitID-login åbner i et vindue på din computer, klar til dit bruger-ID. Skriv det, og godkend i MitID-appen som ved ethvert andet login.</p>'),
 ('<h3>Your AI provider sees it.</h3><p>SundhedMCP runs on your computer, but the medicine, test results and referrals your AI reads are sent to the AI provider you use, under their terms. That is your choice; make it knowingly.</p>',
  '<h3>Din AI-udbyder ser det.</h3><p>SundhedMCP kører på din computer, men den medicin, de prøvesvar og henvisninger, din AI læser, sendes til den AI-udbyder, du bruger, på udbyderens vilkår. Det er dit valg; tag det med åbne øjne.</p>'),
 ('<h3>Nothing stored.</h3><p>Everything lives in memory on your computer and is gone when you stop SundhedMCP. No server, no telemetry, and no SundhedMCP company in between.</p>',
  '<h3>Intet gemmes.</h3><p>Alt ligger i hukommelsen på din computer og forsvinder, når du stopper SundhedMCP. Ingen server, ingen telemetri og intet SundhedMCP-firma imellem.</p>'),
 ('<h2>Run it on your computer.</h2>',
  '<h2>Kør den på din computer.</h2>'),
 ('<p>SundhedMCP runs only locally, next to the AI app on your own computer. There is no hosted version.</p>',
  '<p>SundhedMCP kører kun lokalt, ved siden af AI-appen på din egen computer. Der findes ingen hostet version.</p>'),
 ('<li>Your data leaves your computer only for your AI provider</li><li>Needs Node 24 and Chrome or Edge</li>',
  '<li>Dine data forlader kun din computer til din AI-udbyder</li><li>Kræver Node 24 og Chrome eller Edge</li>'),
 ("Yes: to the AI provider you connect it to. SundhedMCP itself talks only to sundhed.dk, but your AI sends what it reads (medicine, test results, referrals) to its provider, such as Anthropic or OpenAI, under that provider's terms. Read them before you connect your health record.",
  'Ja: til den AI-udbyder, du forbinder den til. SundhedMCP taler selv kun med sundhed.dk, men din AI sender det, den læser (medicin, prøvesvar, henvisninger), til sin udbyder, fx Anthropic eller OpenAI, på udbyderens vilkår. Læs dem, før du forbinder din sundhedsjournal.'),
 ('No. SundhedMCP only fetches and shows your record; it does not interpret results. Your AI can read and summarise it, but it is not your doctor. Talk to your GP or pharmacist before changing how you take any medicine.',
  'Nej. SundhedMCP henter og viser kun din journal; den fortolker ikke resultater. Din AI kan læse og opsummere den, men den er ikke din læge. Tal med din egen læge eller dit apotek, før du ændrer, hvordan du tager din medicin.'),
 ('Does SundhedMCP see my MitID?<span',
  'Ser SundhedMCP mit MitID?<span'),
 ('No. You type your user ID on the real MitID page, in a browser window on your own computer, and approve in your own MitID app, every time. SundhedMCP never sees, stores or passes on MitID credentials.',
  'Nej. Du skriver dit bruger-ID på den rigtige MitID-side, i et browservindue på din egen computer, og godkender i din egen MitID-app, hver gang. SundhedMCP ser, gemmer eller videregiver aldrig MitID-oplysninger.'),
]
da = open('en.source.html').read()
missing = []
for a, b in T:
    if a not in da:
        missing.append(a[:70])
        continue
    da = da.replace(a, b)
print("missing:", missing)
open('da.source.html', 'w').write(da)
